spring.application.name=SpringAddressBook
server.port = 8085


spring.datasource.url=jdbc:mysql://localhost:3306/addressbookdb
spring.datasource.username=root
spring.datasource.password=Aayushi3110
spring.jpa.hibernate.ddl-auto=update
